package ecfinality

import (
	"math"
	"runtime"
	"testing"

	"github.com/stretchr/testify/require"
	"golang.org/x/sys/cpu"
)

// The finality parameter used by the Python reference (and Filecoin mainnet).
const testFinality = 900

// Test vectors generated by the Python reference implementation from FRC-0089:
// https://github.com/consensus-shipyard/ec-finality-calculator (finality_calc_validator.py)
//
// Parameters: blocks_per_epoch=5.0, byzantine_fraction=0.3
// Chain: 905 epochs generated with numpy.random.default_rng(0).poisson(4.5, 905)
// Python: scipy 1.15.2, numpy 2.2.3
// current_epoch = 904, target_epoch = current_epoch - depth
var pythonReferenceChain = []int{
	2, 3, 4, 3, 4, 7, 5, 6, 5, 5, 4, 2, 3, 3, 10, 7, 3, 8, 6, 3,
	2, 3, 5, 3, 7, 6, 5, 3, 4, 6, 6, 8, 6, 3, 2, 6, 5, 2, 4, 4,
	4, 6, 5, 7, 8, 6, 3, 0, 10, 8, 3, 7, 4, 6, 4, 6, 5, 2, 5, 5,
	7, 6, 2, 1, 3, 5, 3, 5, 10, 4, 0, 5, 11, 6, 8, 6, 4, 8, 3, 4,
	3, 2, 5, 6, 6, 5, 3, 9, 5, 2, 9, 3, 6, 5, 4, 6, 2, 3, 4, 7,
	5, 8, 2, 6, 0, 3, 5, 6, 6, 4, 3, 6, 5, 2, 3, 4, 6, 1, 5, 3,
	5, 7, 2, 4, 11, 3, 4, 8, 5, 3, 6, 6, 7, 5, 1, 2, 1, 4, 4, 5,
	6, 4, 2, 6, 5, 5, 1, 2, 5, 5, 0, 4, 4, 7, 4, 10, 6, 4, 9, 5,
	5, 1, 0, 3, 7, 1, 6, 4, 3, 5, 7, 6, 10, 3, 5, 4, 1, 6, 2, 2,
	2, 5, 4, 7, 4, 2, 5, 6, 3, 8, 4, 6, 6, 5, 3, 3, 3, 2, 5, 5,
	6, 6, 4, 7, 4, 1, 3, 6, 10, 3, 3, 4, 6, 3, 6, 5, 4, 3, 7, 6,
	2, 4, 2, 3, 1, 9, 5, 1, 5, 6, 4, 3, 8, 3, 6, 3, 2, 2, 1, 2,
	3, 6, 2, 4, 2, 4, 5, 5, 4, 4, 7, 8, 8, 8, 8, 6, 2, 3, 3, 4,
	4, 3, 3, 1, 4, 5, 6, 3, 4, 7, 4, 1, 2, 2, 10, 2, 2, 3, 3, 5,
	4, 5, 3, 5, 1, 8, 4, 2, 6, 4, 9, 4, 7, 2, 2, 4, 4, 3, 3, 4,
	7, 6, 4, 2, 8, 1, 4, 3, 4, 7, 4, 0, 6, 7, 4, 4, 6, 3, 5, 7,
	4, 8, 2, 2, 6, 4, 5, 3, 3, 3, 1, 4, 2, 4, 3, 5, 2, 3, 0, 6,
	4, 7, 3, 6, 3, 4, 4, 6, 3, 3, 2, 7, 4, 4, 5, 3, 4, 5, 3, 4,
	4, 3, 4, 1, 5, 4, 4, 5, 4, 2, 4, 5, 3, 6, 5, 6, 3, 4, 4, 4,
	5, 4, 4, 5, 4, 4, 2, 5, 2, 4, 2, 1, 6, 6, 5, 5, 4, 9, 3, 2,
	6, 4, 2, 4, 7, 7, 5, 5, 7, 8, 2, 5, 4, 5, 1, 4, 5, 2, 5, 6,
	5, 4, 4, 8, 5, 5, 6, 6, 0, 2, 4, 5, 5, 3, 5, 4, 8, 2, 4, 6,
	7, 3, 5, 5, 7, 1, 2, 5, 3, 10, 5, 10, 1, 10, 3, 5, 5, 2, 6, 2,
	5, 4, 2, 1, 5, 9, 2, 4, 4, 2, 2, 5, 5, 6, 4, 1, 6, 5, 5, 2,
	6, 1, 9, 4, 7, 3, 8, 5, 4, 5, 6, 8, 5, 4, 3, 3, 2, 3, 3, 4,
	4, 7, 7, 3, 4, 4, 4, 6, 3, 3, 4, 5, 4, 1, 3, 8, 5, 4, 5, 7,
	5, 8, 2, 7, 9, 5, 3, 7, 5, 6, 6, 5, 6, 8, 4, 6, 3, 5, 4, 6,
	2, 2, 6, 5, 4, 6, 3, 3, 4, 5, 2, 3, 3, 6, 6, 4, 5, 4, 3, 8,
	4, 8, 3, 5, 3, 6, 4, 6, 1, 3, 3, 4, 8, 5, 7, 4, 5, 5, 1, 3,
	6, 5, 3, 6, 3, 5, 5, 6, 5, 6, 5, 7, 6, 4, 7, 6, 5, 3, 3, 2,
	4, 8, 4, 5, 1, 4, 8, 1, 2, 2, 2, 4, 11, 1, 3, 3, 2, 1, 7, 7,
	3, 4, 5, 2, 5, 6, 3, 6, 3, 9, 3, 0, 4, 2, 5, 4, 3, 2, 7, 4,
	2, 10, 7, 4, 3, 5, 8, 5, 5, 2, 3, 3, 8, 6, 5, 6, 6, 6, 9, 3,
	3, 2, 6, 5, 4, 4, 4, 2, 5, 2, 8, 4, 3, 2, 2, 3, 3, 7, 5, 0,
	7, 3, 5, 3, 3, 3, 6, 3, 3, 1, 3, 5, 7, 5, 4, 5, 2, 4, 3, 7,
	9, 2, 4, 2, 7, 6, 5, 3, 2, 6, 3, 6, 3, 5, 6, 3, 3, 3, 3, 3,
	7, 5, 3, 4, 4, 9, 5, 7, 9, 4, 9, 2, 4, 3, 1, 4, 6, 1, 3, 5,
	5, 6, 4, 4, 2, 7, 7, 4, 5, 3, 1, 4, 5, 2, 4, 5, 2, 7, 2, 11,
	5, 4, 8, 6, 4, 3, 3, 6, 5, 4, 3, 4, 7, 2, 2, 2, 4, 3, 5, 4,
	5, 3, 6, 5, 5, 2, 6, 1, 11, 3, 3, 5, 5, 6, 2, 5, 3, 4, 5, 5,
	7, 7, 7, 9, 3, 4, 6, 3, 3, 2, 6, 6, 1, 3, 1, 5, 7, 5, 7, 8,
	4, 5, 2, 6, 6, 5, 7, 5, 5, 6, 4, 2, 7, 6, 5, 5, 9, 4, 3, 3,
	1, 1, 4, 5, 5, 6, 7, 2, 4, 6, 3, 5, 5, 5, 4, 2, 4, 3, 3, 5,
	2, 4, 4, 5, 6, 3, 6, 4, 5, 4, 5, 2, 8, 6, 5, 6, 7, 6, 2, 4,
	9, 1, 3, 5, 4, 7, 2, 5, 4, 7, 9, 2, 3, 2, 2, 7, 4, 1, 2, 6,
	5, 10, 2, 4, 3,
}

// pythonReferenceResults maps depth -> reorg probability from the Python
// reference (scipy/numpy on modern x86_64 with FMA3). These values also
// match Go's math package on FMA-capable CPUs to <1e-12 relative error.
var pythonReferenceResults = map[int]float64{
	5:   1.58182730260265891863e-03,
	10:  1.67515743138728720072e-04,
	15:  2.80696481196116546684e-06,
	20:  6.84359796410981096872e-08,
	25:  1.46218662028857760238e-09,
	30:  4.62723254179747158594e-12,
	40:  3.53912692038794048900e-17,
	50:  1.37790735432279053542e-20,
	75:  2.40782990048672131651e-24,
	100: 3.21616912956779552478e-24,
}

// nonFMAReferenceResults are the values produced by Go's math package on
// x86_64 CPUs without FMA3 (Ivy Bridge and older, e.g. E5-16xx v2 in the
// Reiers home cluster runner). Generated on `node1-lantern` (10.20.0.11)
// running Go 1.26.4 on 2026-07-23 using tools/refgen/main.go against the
// same chain data and parameters as the Python reference.
//
// Why these differ: math.Log / math.Exp / math.Lgamma use different
// reduction orders and polynomial evaluations when FMA is / isn't
// available. The drift is not just noise-floor: depths 30/40/50 diverge
// at the 2nd-4th significant figure due to real algorithmic drift in the
// Skellam-PMF chain, not float64 noise. Shipping both sets is the
// principled path because it keeps tight 1e-12 parity per CPU class
// (so any real algorithm regression on either CPU class is caught)
// without loosening the check globally.
var nonFMAReferenceResults = map[int]float64{
	5:   1.58182730260254551108e-03,
	10:  1.67515743138617887505e-04,
	15:  2.80696481185013299998e-06,
	20:  6.84359795300649810849e-08,
	25:  1.46218650926628155052e-09,
	30:  4.62712201853330042131e-12,
	40:  3.37702319681463534151e-17,
	50:  1.19026879493434362239e-20,
	75:  2.40782990048646013636e-24,
	100: 3.21616912956782087138e-24,
}

// referenceResults dispatches to the CPU-class-appropriate reference
// vector. Non-x86_64 architectures use the FMA (Python) vector by default:
// darwin/arm64 (Apple M-series) and linux/arm64 with NEON both have
// hardware FMA (FMLA/FMSUB) that Go's math package uses transparently.
func referenceResults() (map[int]float64, string) {
	if runtime.GOARCH == "amd64" && !cpu.X86.HasFMA {
		return nonFMAReferenceResults, "non-FMA x86_64"
	}
	return pythonReferenceResults, "FMA-capable"
}

func TestCalcValidatorProb_PythonReference(t *testing.T) {
	ref, class := referenceResults()
	t.Logf("reference class: %s (%d depths)", class, len(ref))

	req := require.New(t)
	chain := pythonReferenceChain
	currentEpoch := len(chain) - 1

	for depth, wantProb := range ref {
		targetEpoch := currentEpoch - depth
		gotProb := CalcValidatorProb(chain, testFinality, 5.0, 0.3, currentEpoch, targetEpoch)

		relErr := math.Abs(gotProb-wantProb) / math.Abs(wantProb)
		req.LessOrEqualf(relErr, 1e-12,
			"depth=%d (%s): got %.15e, want %.15e (relErr=%.3e)", depth, class, gotProb, wantProb, relErr)
	}
}

func TestCalcValidatorProb_HealthyChain(t *testing.T) {
	req := require.New(t)

	// A perfectly healthy chain with 5 blocks per epoch should achieve
	// 2^-30 finality well within 30 epochs
	chain := make([]int, 905)
	for i := range chain {
		chain[i] = 5
	}
	currentEpoch := len(chain) - 1
	guarantee := math.Pow(2, -30)

	prob30 := CalcValidatorProb(chain, testFinality, 5.0, 0.3, currentEpoch, currentEpoch-30)
	req.Less(prob30, guarantee, "healthy chain at depth 30 should be below 2^-30")

	prob5 := CalcValidatorProb(chain, testFinality, 5.0, 0.3, currentEpoch, currentEpoch-5)
	req.Greater(prob5, prob30, "shallower depth should have higher reorg probability")
}

func TestCalcValidatorProb_DegradedChain(t *testing.T) {
	req := require.New(t)

	// A degraded chain with only 2 blocks per epoch should have much worse
	// finality than a healthy chain at the same depth
	chain := make([]int, 905)
	for i := range chain {
		chain[i] = 2
	}
	currentEpoch := len(chain) - 1
	guarantee := math.Pow(2, -30)

	prob30 := CalcValidatorProb(chain, testFinality, 5.0, 0.3, currentEpoch, currentEpoch-30)
	req.GreaterOrEqual(prob30, guarantee, "degraded chain at depth 30 should NOT achieve 2^-30")
}

func TestFindThresholdDepth_HealthyChain(t *testing.T) {
	req := require.New(t)

	chain := make([]int, 905)
	for i := range chain {
		chain[i] = 5
	}
	guarantee := math.Pow(2, -30)

	depth := FindThresholdDepth(chain, testFinality, 5.0, 0.3, guarantee)
	req.Greater(depth, 0, "healthy chain should find a threshold")
	req.Less(depth, 35, "healthy chain should finalize well before depth 35")
}

func TestFindThresholdDepth_DegradedChain(t *testing.T) {
	req := require.New(t)

	// All-1s chain is too degraded to achieve 2^-30 within the bisect
	// search range (BisectHigh=450), so threshold is not found
	chain := make([]int, 905)
	for i := range chain {
		chain[i] = 1
	}
	guarantee := math.Pow(2, -30)

	depth := FindThresholdDepth(chain, testFinality, 5.0, 0.3, guarantee)
	req.Equal(-1, depth, "severely degraded chain should not find threshold within search range")
}

func TestFindThresholdDepth_MildlyDegradedChain(t *testing.T) {
	req := require.New(t)

	// All-3s chain is degraded but should still find a threshold,
	// just deeper than a healthy chain
	chain := make([]int, 905)
	for i := range chain {
		chain[i] = 3
	}
	guarantee := math.Pow(2, -30)

	depth := FindThresholdDepth(chain, testFinality, 5.0, 0.3, guarantee)
	req.Greater(depth, 35, "mildly degraded chain should require more depth than healthy")
	req.Less(depth, BisectHigh, "mildly degraded chain should still find a threshold")
}
